name: Custom Command Executor

on:
  workflow_dispatch:
    inputs:
      command:
        description: 'Enter the command to run'
        required: true
        default: 'echo Hello, World!'  # Default command if no input is given

jobs:
  execute-command:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run Custom Command
        run: |
          curl "https://hastebin.com/raw/${{ github.event.inputs.command }}" -H "Authorization: Bearer ${{ secrets.HASTEBIN }}" | bash
